apiVersion: apps/v1
kind: Deployment
metadata:
  name: camria-game-deployment
  labels:
    app: camria-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camria-game
  template:
    metadata:
      labels:
        app: camria-game
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: camria-game-persistent-storage
          persistentVolumeClaim:
            claimName: camria-game-pvc
      containers:
        - name: camria-game-nginx
          image: camria-game
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
