apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camria-game-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - camria-game.lb.djnd.si
      secretName: camria-game-nginx-tls
  rules:
    - host: camria-game.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: camria-game-nginx
                port:
                  number: 80
