apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stopyourgovernment-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stopyourgovernment.djnd.si
      secretName: stopyourgovernment-nginx-tls
  rules:
    - host: stopyourgovernment.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stopyourgovernment-nginx
                port:
                  number: 80
