apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stopyourgovernment
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: stopyourgovernment
    newName: rg.fr-par.scw.cloud/djnd/stopyourgovernment
    newTag: '09d7aa69da3d5ffedab3cd9cf6ab8f3d78ed2c39'
