apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: camria
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: camria-game
    newName: rg.fr-par.scw.cloud/djnd/camria-game
    newTag: 'd51003d320fa0415dd8632269f54a1ff6bbe2d16'
