apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stopyourgovernment
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: stopyourgovernment
    newName: rg.fr-par.scw.cloud/djnd/stopyourgovernment
    newTag: '65f5d423adf86a0a1403a951092d6a0a69d37e81'
